name: 'Setup'

runs:
  using: "composite"
  steps:
    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        
    - name: Install cross
      uses: taiki-e/install-action@v2
      with:
        tool: cross
