name: 'Setup'

runs:
  using: "composite"
  steps:
    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{ matrix.target }}
